import React from 'react';
import { 
  BookOpen, ShieldCheck, Cpu, Award, ArrowLeft, 
  Terminal, Search, Zap, MessageSquare 
} from 'lucide-react';

function AboutProject({ setActiveTab, isPublic = false }) {
  const pillars = [
    {
      icon: <ShieldCheck size={24} style={{ color: 'var(--color-emerald)' }} />,
      title: "100% Offline-First Data Privacy",
      desc: "Zero external API calls. Student notes, exam papers, and question banks stay strictly inside your campus intranet server perimeter."
    },
    {
      icon: <Cpu size={24} style={{ color: 'var(--color-violet)' }} />,
      title: "Grounded RAG Senior AI",
      desc: "Answers generated by Senior AI are strictly grounded in verified local PDF documents, displaying clickable source citations [1], [2]."
    },
    {
      icon: <Award size={24} style={{ color: 'var(--color-amber)' }} />,
      title: "Gamified Peer Contributions",
      desc: "Graduating seniors earn contribution points, streak flames, and prestige badges for sharing notes and real placement interview reviews."
    },
    {
      icon: <Zap size={24} style={{ color: 'var(--color-blue)' }} />,
      title: "Institutional Placement Vault",
      desc: "Eliminates repeated effort by capturing real company interview patterns (Zoho, Microsoft, TCS) and coding questions year after year."
    }
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, maxWidth: 1000, margin: '0 auto' }}>
      {/* Back Header - Only shown inside main app */}
      {!isPublic && (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <button 
            className="btn btn-secondary btn-sm" 
            onClick={() => setActiveTab ? setActiveTab('dashboard') : window.history.back()}
          >
            <ArrowLeft size={14} /> Back to Dashboard
          </button>
          <span style={{ fontSize: 12, fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px' }}>
            Platform Vision & Mission
          </span>
        </div>
      )}

      {/* Hero Banner */}
      <div className="panel" style={{
        background: 'linear-gradient(135deg, rgba(59,130,246,0.08) 0%, rgba(139,92,246,0.06) 100%)',
        border: '1px solid rgba(59,130,246,0.2)',
        padding: '32px 36px'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 12 }}>
          <img src="/ui_assets/acadence_ai_logo.png" alt="Acadence AI Logo" style={{ width: 44, height: 44 }} />
          <div>
            <h1 style={{ margin: 0, fontSize: 24, fontWeight: 800, fontFamily: 'var(--font-heading)' }}>
              About Acadence AI
            </h1>
            <p style={{ margin: 0, fontSize: 13.5, color: 'var(--color-blue)', fontWeight: 600 }}>
              The Offline-First Campus Knowledge & Placement Intelligence Ecosystem
            </p>
          </div>
        </div>

        <p style={{ fontSize: 14.5, color: 'var(--text-secondary)', lineHeight: 1.7, margin: '16px 0 0' }}>
          Every year, graduating college seniors leave behind invaluable study notes, previous exam solutions, and placement interview memories. Without a central campus memory system, incoming juniors start from scratch, repeating the exact same efforts. 
          <br /><br />
          <strong>Acadence AI</strong> solves this knowledge decay by serving as an intelligent, self-sustaining university repository powered by local RAG vector search and privacy-focused local AI.
        </p>
      </div>

      {/* Core Pillars */}
      <div>
        <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
          <Terminal size={18} style={{ color: 'var(--color-blue)' }} /> Core Pillars & Value Proposition
        </h3>
        <div className="grid-2" style={{ gap: 16 }}>
          {pillars.map((p, idx) => (
            <div key={idx} className="panel" style={{ padding: '20px 24px' }}>
              <div style={{ marginBottom: 12 }}>{p.icon}</div>
              <h4 style={{ margin: '0 0 6px', fontSize: 15, fontWeight: 700, color: 'var(--text-primary)' }}>
                {p.title}
              </h4>
              <p style={{ margin: 0, fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                {p.desc}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Footer CTA */}
      <div className="panel" style={{ textAlign: 'center', padding: '32px' }}>
        <h3 style={{ margin: '0 0 8px', fontSize: 18, fontWeight: 700 }}>Ready to explore the knowledge hub?</h3>
        <p style={{ fontSize: 13.5, color: 'var(--text-secondary)', marginBottom: 20 }}>
          Start querying verified notes or chat with Senior AI right now.
        </p>
        <div style={{ display: 'flex', justifyContent: 'center', gap: 12 }}>
          <button className="btn btn-primary" onClick={() => setActiveTab && setActiveTab('ai-chat')}>
            <MessageSquare size={15} /> Ask Senior AI
          </button>
          <button className="btn btn-secondary" onClick={() => setActiveTab && setActiveTab('explorer')}>
            <Search size={15} /> Explore Documents
          </button>
        </div>
      </div>
    </div>
  );
}

export default AboutProject;
